### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by dg1kwa** [geeekpi/absminitowerkit#11]
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    For more information visit http://rptl.io/venv

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
dir

then not work:

python3 sysinfo.py
Traceback (most recent call last):
  File "/home/pi/absminitowerkit/sysinfo.py", line 13, in <module>
    from demo_opts import get_device
ModuleNotFoundError: No module named 'demo_opts'

**Comment by Robpi4b5** [comment]
I am having the same issue. Have tried a number of ways to get around it, with no luck.

**Comment by dg1kwa** [comment]
> I am having the same issue. Have tried a number of ways to get around it, with no luck.

I try next days with an Raspbian 11

**Comment by yoyojacky** [comment]
please execute this command in the luma.examples folder:
```bash
sudo -H pip3 install -e .  --break-system-packages 
```
and then get into the luma.exampls/examples folder and try again.
