### ISSUE TITLE
Does this work on Home Assistant OS

### ISSUE THREAD

**Issue by HuggiesHA** [geeekpi/absminitowerkit#14]
Hello

I can see from the instruction's, the guide states Raspberry OS but can it be installed in the Home Assistant OS the same way or is it not compatible with HA OS in regards to the display and led lights?

If it does work, do you have a guide or is it the same step in the guide.

Just trying to confirm if I need to return the item or keep it.

**Comment by yoyojacky** [comment]
Please try our new installation script  on Raspberry Pi OS bookworm 64bit, it has been tested .

**Comment by yoyojacky** [comment]
Could you please show me your HA OS version ?  or just use the same script to install and try it, and you can paste the error during installation, i am going to help you out.

**Comment by yoyojacky** [comment]
Home Assistant Operating System uses Docker as its container engine. By default it deploys the Home Assistant Supervisor as a container. Home Assistant Supervisor in turn uses the Docker container engine to control Home Assistant Core and Add-Ons in separate containers. Home Assistant Operating System is not based on a regular Linux distribution like Ubuntu. It is built using [Buildroot](https://buildroot.org/) and it is optimized to run Home Assistant. It targets single board compute (SBC) devices like the Raspberry Pi or ODROID but also supports x86-64 systems with UEFI.
according to this URL https://github.com/home-assistant/operating-system 
The Home Assistant operating system is not based on conventional Linux distributions such as Ubuntu, so the OLED screen driver and MOODlight
The required driver may not be included in the system's package management. If you must use home assistant, you can also try to install docker directly in raspberry pi OS, and then run a container that includes home assistant.
