### ISSUE TITLE
IP Address

### ISSUE THREAD

**Issue by djackson-telaid** [geeekpi/absminitowerkit#3]
How can I show the eth0 IP address on the LCD screen instead of the network counters?

**Comment by UseLessUK** [comment]
I added;
`def system_ip():
    # IP
    ip = sp.getoutput("hostname -I").split(' ')[0]
    return "IP:%s" % (ip)
`
and then changed the first line to show the IP address instead of the load
`    with canvas(device) as draw:
#        draw.text((0, 1), cpu_usage(), font=font2, fill="white")
        draw.text((0,1), system_ip(), font=font2, fill="white")
`

**Comment by yoyojacky** [comment]
or replace the the command with :   ifconfig  eth0 |grep 'inet' | head -n1 | awk ‘{print $2}'

**Comment by yoyojacky** [comment]
```bash
def ip_eth0():
    # get  IP address
    ip = sp.getoutput("ifconfig eth0 |grep 'inet' | head -n1 | awk ‘{print $2}'").strip(' ')
    return "IP:%s" % (ip)
```
and then changed the first line to show the IP address instead of the load

    with canvas(device) as draw:
#        draw.text((0, 1), cpu_usage(), font=font2, fill="white")
        draw.text((0,1), ip_eth0(), font=font2, fill="white")
